/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_ufl_cise_klu_wrapper_SuperMatrix */

#ifndef _Included_edu_ufl_cise_klu_wrapper_SuperMatrix
#define _Included_edu_ufl_cise_klu_wrapper_SuperMatrix
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_ufl_cise_klu_wrapper_SuperMatrix
 * Method:    set_native
 * Signature: (IID)V
 */
JNIEXPORT void JNICALL Java_edu_ufl_cise_klu_wrapper_SuperMatrix_set_1native
  (JNIEnv *, jobject, jint, jint, jdouble);

/*
 * Class:     edu_ufl_cise_klu_wrapper_SuperMatrix
 * Method:    get_native
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_edu_ufl_cise_klu_wrapper_SuperMatrix_get_1native
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     edu_ufl_cise_klu_wrapper_SuperMatrix
 * Method:    release_CompCol_Matrix
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_edu_ufl_cise_klu_wrapper_SuperMatrix_release_1CompCol_1Matrix
  (JNIEnv *, jobject, jobject);

/*
 * Class:     edu_ufl_cise_klu_wrapper_SuperMatrix
 * Method:    cols_native
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_ufl_cise_klu_wrapper_SuperMatrix_cols_1native
  (JNIEnv *, jobject);

/*
 * Class:     edu_ufl_cise_klu_wrapper_SuperMatrix
 * Method:    rows_native
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_ufl_cise_klu_wrapper_SuperMatrix_rows_1native
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
